FROM python:3.13.0-slim

WORKDIR /app

# Copier tous les fichiers nécessaires
COPY model/cleaned_data.csv .
COPY model/model.pkl .
COPY model/scaler.pkl .
COPY model/model_service.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5001

CMD ["python", "model_service.py"]